# Generated by Django 5.0.14 on 2026-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('BookingRequest', 'Booking Request'), ('BookingApproval', 'Booking Approved'), ('BookingRejection', 'Booking Rejected'), ('BookingCancellation', 'Booking Cancelled'), ('RideStarted', 'Ride Started'), ('RideCompleted', 'Ride Completed'), ('WalletCredit', 'Wallet Credited'), ('WalletDebit', 'Wallet Debited')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
