# Generated by Django 5.0.14 on 2026-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_otpcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpcode",
            name="email",
        ),
        migrations.AddField(
            model_name="otpcode",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
        ),
    ]
