# Generated by Django 5.0.14 on 2026-07-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_otpcode_email_otpcode_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
