# Generated by Django 5.0.14 on 2026-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_otpcode_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, default="Engineering", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="office_seat_desk",
            field=models.CharField(
                blank=True, default="Gandhinagar HQ", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reporting_manager",
            field=models.CharField(blank=True, default="Raj Patel", max_length=100),
        ),
    ]
