# Generated by Django 5.0.14 on 2026-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_trips', models.IntegerField(default=0)),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_co2_saved', models.FloatField(default=0.0)),
                ('total_fuel_saved', models.FloatField(default=0.0)),
                ('total_money_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, unique=True)),
                ('total_trips_taken', models.IntegerField(default=0)),
                ('total_trips_offered', models.IntegerField(default=0)),
                ('total_co2_saved', models.FloatField(default=0.0)),
                ('total_fuel_saved', models.FloatField(default=0.0)),
                ('total_money_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
