# Generated by Django 5.0.14 on 2026-07-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailOTP",
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
