# Generated by Django 5.0.14 on 2026-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                (
                    "pickup_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("destination_location", models.CharField(max_length=255)),
                (
                    "destination_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("travel_date", models.DateField()),
                ("travel_time", models.TimeField()),
                ("available_seats", models.PositiveIntegerField()),
                ("fare_per_seat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "route_preview",
                    models.JSONField(
                        blank=True,
                        help_text="Stores route coordinates list or GeoJSON",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("recurring", models.BooleanField(default=False)),
                (
                    "recurring_pattern",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Daily, Weekly",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
