# Generated by Django 5.0.14 on 2026-07-18 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Honda City, Tesla Model 3", max_length=100
                    ),
                ),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("cng", "CNG"),
                            ("electric", "Electric"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "mileage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="km per liter or km per kWh",
                        max_digits=5,
                    ),
                ),
                ("seat_capacity", models.PositiveIntegerField(default=4)),
                (
                    "vehicle_image",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
