# Generated by Django 5.0.14 on 2026-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(max_length=255)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_address', models.CharField(max_length=255)),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('departure_time', models.DateTimeField()),
                ('total_seats', models.IntegerField(default=4)),
                ('available_seats', models.IntegerField(default=4)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Published', max_length=20)),
                ('estimated_distance', models.FloatField(default=0.0)),
                ('estimated_duration', models.FloatField(default=0.0)),
                ('estimated_co2_saved', models.FloatField(default=0.0)),
                ('estimated_fuel_saved', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
