# Generated by Django 5.0.14 on 2026-07-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ride",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="rides.ride",
            ),
        ),
    ]
