# Generated by Django 5.0.14 on 2026-07-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Ride Booked"),
                            ("started", "Ride Started"),
                            ("in_progress", "Ride In Progress"),
                            ("completed", "Ride Completed"),
                            ("cancelled", "Ride Cancelled"),
                        ],
                        default="booked",
                        max_length=20,
                    ),
                ),
                (
                    "driver_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "driver_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "distance_covered",
                    models.DecimalField(
                        decimal_places=2, default=0.0, help_text="In km", max_digits=10
                    ),
                ),
                ("eta_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(help_text="1 to 5 stars")),
                ("review_text", models.TextField(blank=True)),
                (
                    "role_rated",
                    models.CharField(
                        choices=[("driver", "Driver"), ("passenger", "Passenger")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
    ]
