# Generated by Django 5.0.14 on 2026-07-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_price",
                    models.DecimalField(decimal_places=2, default=103.5, max_digits=10),
                ),
                (
                    "default_fuel_efficiency",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
                ),
                (
                    "co2_factor",
                    models.DecimalField(decimal_places=2, default=0.15, max_digits=10),
                ),
                ("max_seats_limit", models.PositiveIntegerField(default=6)),
                ("require_license_for_driver", models.BooleanField(default=True)),
            ],
        ),
    ]
